Fix bug in useMMKV
mrousavy/react-native-mmkv pull request #244
Opened 2021-12-02 08:12 UTC by robinsoncol

When we initially call useMMKV, `lastConfiguration` is initialized, causing `!isConfigurationEqual(lastConfiguration.current, configuration)` to be `false` and we don't save a new MMKV instance. The solution I propose should fix this issue.

2021-12-02 08:18 UTC, mrousavy requested changes
Thanks for the PR! I prefer to use strict null checks (`== null`), could you please update that? Otherwise good to go, can't believe I missed that 😅

2021-12-02 08:18 UTC, mrousavy commented on src/hooks.ts
> +  if (!lastConfiguration.current || !isConfigurationEqual(lastConfiguration.current, configuration)) {
```suggestion
  if (lastConfiguration.current == null || !isConfigurationEqual(lastConfiguration.current, configuration)) {
```

2021-12-02 08:55 UTC, robinsoncol commented on src/hooks.ts
> +  if (!lastConfiguration.current || !isConfigurationEqual(lastConfiguration.current, configuration)) {
Done and thanks!

2021-12-10 08:54 UTC, merged

2021-12-10 08:54 UTC, mrousavy commented
Thank you!