Update docs with react-query example
mrousavy/react-native-mmkv pull request #473
Opened 2022-11-03 13:06 UTC by Navipro70

2022-11-03 13:17 UTC, mrousavy requested changes

2022-11-03 13:17 UTC, mrousavy commented on README.md
> +* [Using MMKV with react-query](./docs/WRAPPER_REACTQUERY.md)
Can you rename the file to `WRAPPER_REACT_QUERY.md` (`_` between REACT and QUERY)?

2022-11-03 13:17 UTC, mrousavy commented on docs/WRAPPER_REACTQUERY.md
> +If you want to use MMKV with [react-query](https://tanstack.com/query/v4/docs/plugins/createSyncStoragePersister), create the following `clientPersister` object:
Maybe also mention that you need to install the `@tanstack/query-sync-storage-persister` package?

2022-11-03 13:17 UTC, mrousavy commented on docs/WRAPPER_REACTQUERY.md
> +export const clientStorage = {
I don't think this should be exported, should it?

2022-11-03 13:17 UTC, mrousavy commented on docs/WRAPPER_REACTQUERY.md
> +const clientPersister = createSyncStoragePersister({ storage: clientPersistStorage });
Looks like this should be exported though!

2022-11-03 13:17 UTC, mrousavy commented
Thanks for your PR! Left some minor tweaks to perfect it but otherwise looks good!

2023-02-13 09:34 UTC, Navipro70 commented
@mrousavy 
Check please, I assume we can merge it)

2023-02-13 09:37 UTC, mrousavy commented
Ah yep, looks good - thanks! :)

2023-02-13 09:37 UTC, merged