feat: If AppGroup defined in plist apply group dir.
mrousavy/react-native-mmkv pull request #703
Opened 2024-07-16 16:05 UTC by calism2

This commit adds functionality to check if an AppGroup is defined in the info.plist. If it is, the group directory is applied, allowing for shared storage between the main app and its extensions.

Closes #702

2024-07-17 10:55 UTC, mrousavy requested changes
thanks for the PR! Just a few minor nitpicks.

2024-07-17 10:55 UTC, mrousavy commented on package/cpp/MmkvHostObject.cpp
> +#include <Foundation/Foundation.h>
Please move the include up to the other header includes. Don't forget to wrap it in `#ifdef __APPLE__`  again.

2024-07-17 10:55 UTC, mrousavy commented on package/cpp/MmkvHostObject.cpp
> +  if (appGroup) {
```suggestion
  if (appGroup != nil) {
```

2024-07-17 10:55 UTC, mrousavy commented on package/cpp/MmkvHostObject.cpp
> +    MmkvLogger::log("RNMMKV", "Path ignored, AppGroup defined plist");
```suggestion
    MmkvLogger::log("RNMMKV", "Info.plist specifies a custom AppGroup - ignoring `path`...");
```

2024-07-17 10:55 UTC, mrousavy commented on package/cpp/MmkvHostObject.cpp
> +    std::string groupDirStr(groupDirCStr);
```suggestion
    std::string groupDirStr = groupDir.UTF8String;
```

2024-07-17 10:55 UTC, mrousavy commented on package/cpp/MmkvHostObject.cpp
> +
```suggestion
```

2024-07-17 12:18 UTC, calism2 commented
Hi,

Thank you for your fast response. I have implemented the requested changes. Additionally, if the AppGroup capability is not added correctly, the app will throw a null pointer exception, which might be difficult for JavaScript developers to trace. Therefore, I have added a custom runtime error to handle this scenario.

2024-07-22 15:08 UTC, mrousavy commented
Hey! Thanks for the updates, but I felt like moving `getAppGroup` into `MmkvPlatformContext` made more sense, as it is iOS-specific code and I don't want to cram that into the shared .cpp file.

Let me know what you think: https://github.com/mrousavy/react-native-mmkv/pull/705

2024-07-22 15:28 UTC, closed without merging